import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Shield, Zap, FileText } from 'lucide-react';

export default function Home() {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.2 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.5, ease: "easeOut" }
    }
  };

  return (
    <div className="flex-1 flex flex-col items-center justify-center relative overflow-hidden bg-gradient-to-br from-slate-50 via-white to-blue-50/50">
      {/* Abstract Background Shapes */}
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-primary/10 rounded-full blur-[100px] animate-pulse" style={{ animationDuration: '4s' }} />
      <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-blue-400/10 rounded-full blur-[100px] animate-pulse" style={{ animationDuration: '6s' }} />

      <motion.div 
        className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-20 text-center relative z-10"
        variants={containerVariants}
        initial="hidden"
        animate="visible"
      >
        <motion.div variants={itemVariants} className="inline-flex items-center space-x-2 bg-white px-4 py-2 rounded-full shadow-sm border border-slate-200 mb-8">
          <span className="flex h-2 w-2 rounded-full bg-primary animate-pulse"></span>
          <span className="text-sm font-medium text-slate-600">AI-Powered Diagnostic Assistant</span>
        </motion.div>

        <motion.h1 variants={itemVariants} className="text-5xl md:text-7xl font-extrabold text-slate-900 tracking-tight mb-6">
          Advanced <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-blue-600">Kidney Disease</span> Detection
        </motion.h1>

        <motion.p variants={itemVariants} className="mt-4 text-xl text-slate-600 max-w-3xl mx-auto mb-10 leading-relaxed">
          Upload hyperspectral images of kidney tissue for instant, highly accurate analysis powered by Deep Learning. Get comprehensive medical reports generated by advanced LLMs in seconds.
        </motion.p>

        <motion.div variants={itemVariants} className="flex flex-col sm:flex-row justify-center gap-4">
          <Link
            to="/upload"
            className="inline-flex items-center justify-center px-8 py-4 text-base font-medium rounded-xl text-white bg-primary hover:bg-primary-dark transition-all shadow-lg hover:shadow-primary/30 transform hover:-translate-y-0.5"
          >
            Start Analysis
            <ArrowRight className="ml-2 h-5 w-5" />
          </Link>
          <Link
            to="/about"
            className="inline-flex items-center justify-center px-8 py-4 text-base font-medium rounded-xl text-slate-700 bg-white border border-slate-200 hover:bg-slate-50 transition-all shadow-sm"
          >
            Learn How It Works
          </Link>
        </motion.div>
      </motion.div>

      {/* Features Section */}
      <motion.div 
        className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 z-10"
        variants={containerVariants}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-100px" }}
      >
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {[
            {
              icon: <Zap className="h-6 w-6 text-yellow-500" />,
              title: "Rapid Inference",
              description: "Get precise classification results in milliseconds using an optimized, lightweight MobileNetV3 architecture."
            },
            {
              icon: <Shield className="h-6 w-6 text-green-500" />,
              title: "High Accuracy",
              description: "Trained on over 10,000 hyperspectral images ensuring >99% diagnostic accuracy in testing."
            },
            {
              icon: <FileText className="h-6 w-6 text-purple-500" />,
              title: "Detailed Reports",
              description: "Comprehensive medical insights and treatment suggestions powered locally by Mistral 7B."
            }
          ].map((feature, idx) => (
            <motion.div 
              key={idx} 
              variants={itemVariants} 
              whileHover={{ y: -5, scale: 1.02 }}
              className="bg-white/80 backdrop-blur-sm p-8 rounded-3xl shadow-sm border border-slate-100 hover:shadow-lg hover:border-primary/20 transition-all duration-300"
            >
              <div className="bg-slate-50 w-14 h-14 rounded-2xl flex items-center justify-center mb-6 shadow-inner">
                {feature.icon}
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-3">{feature.title}</h3>
              <p className="text-slate-600 leading-relaxed">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* How It Works Section */}
      <motion.div 
        className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 z-10 border-t border-slate-100"
        variants={containerVariants}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-100px" }}
      >
        <div className="text-center mb-16">
          <motion.h2 variants={itemVariants} className="text-3xl md:text-4xl font-extrabold text-slate-900 mb-4">How It Works</motion.h2>
          <motion.p variants={itemVariants} className="text-lg text-slate-500">Three simple steps to AI-powered diagnostics</motion.p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-12 relative">
          {/* Connector Line (Desktop) */}
          <div className="hidden md:block absolute top-1/2 left-[15%] right-[15%] h-0.5 bg-gradient-to-r from-primary/10 via-primary/30 to-primary/10 -translate-y-1/2 z-0" />
          
          {[
            { step: "01", title: "Upload Image", desc: "Securely upload your hyperspectral kidney scan." },
            { step: "02", title: "AI Analysis", desc: "Our CNN model analyzes the tissue for anomalies." },
            { step: "03", title: "Get Results", desc: "Receive an instant diagnosis and LLM-generated report." }
          ].map((item, idx) => (
            <motion.div key={idx} variants={itemVariants} className="relative z-10 flex flex-col items-center text-center">
              <div className="w-16 h-16 rounded-full bg-white border-4 border-slate-50 shadow-md flex items-center justify-center text-xl font-black text-primary mb-6">
                {item.step}
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-2">{item.title}</h3>
              <p className="text-slate-500">{item.desc}</p>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </div>
  );
}
